// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyrnodwzuuqgksbwjxnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5cm5vZHd6dXVxZ2tzYndqeG5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTEyODQsImV4cCI6MjA2MzcyNzI4NH0.JjodyYEnwj9F66_zrYB2xWc8aFY7pVMDsHmy4-GRnI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);